### PR TITLE
Ukrainian translation

### PR DESCRIPTION
**Pull request by wtlgo**
It's in the title

### CODE REVIEW

**Comment by blablubbabc** [comment]
Please let me know if this is ready to be merged

**Comment by wtlgo** [comment]
It's done, but I want to recheck the grammar and be sure that some words match Minecraft's official Ukrainian translation. Unfortunately enough, it's late already, so my mind isn't in the brightest shape right now, so I'll do it tomorrow. Sorry that it takes this long.

**Comment by wtlgo** [comment]
@blablubbabc it's ready

**Comment by blablubbabc** [comment]
I have squashed all changes and re-applied them on top of the v2.17.0 branch.

Thank you!

**Pull request merged**
